### ISSUE TITLE
Error - npm start

### ISSUE THREAD

**Issue by oiacrasec** [geops/ole2#32]
Hello, i need help to get the project working, complete log of this run:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@5.6.0
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ole@0.0.1~prestart: ole@0.0.1
6 info lifecycle ole@0.0.1~start: ole@0.0.1
7 verbose lifecycle ole@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle ole@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/cesar/WebstormProjects/ole2/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle ole@0.0.1~start: CWD: /home/cesar/WebstormProjects/ole2
10 silly lifecycle ole@0.0.1~start: Args: [ '-c', 'webpack-dev-server --progress --watch' ]
11 info lifecycle ole@0.0.1~start: Failed to exec start script
12 verbose stack Error: ole@0.0.1 start: `webpack-dev-server --progress --watch`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid ole@0.0.1
14 verbose cwd /home/cesar/WebstormProjects/ole2
15 verbose Linux 4.10.0-42-generic
16 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "start" "--scripts-prepend-node-path=auto"
17 verbose node v8.9.3
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error ole@0.0.1 start: `webpack-dev-server --progress --watch`
23 error spawn ENOENT
24 error Failed at the ole@0.0.1 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by lb1c** [comment]
@mhaertwig  i cannot reproduce this specific error, but the `npm start` definitly raises an error during webpack compile:

https://gist.github.com/lb1c/a32733c954bb53e99d9a291145bb6d0f

**Comment by drnextgis** [comment]
Cannot reproduce this issue here with the same versions of nodejs and npm as provided by @lb1c.
